updater:
  url: https://update.idb-lab.de/
launcher:
  start:
    fileName: "engine.exe"
    arguments: "/load /config debug"
    workingDirectory: ""
    resolveFromAppDirectory: true
    closeUpdaterOnSuccess: true
  settings:
    fileName: "engine.exe"
    arguments: "/setup"
    workingDirectory: ""
    resolveFromAppDirectory: true
    closeUpdaterOnSuccess: false
  website:
    url: http://www.idb-lab.de/
ui:
  language: en
window:
  icon: Icons:app.ico
