// Copyright (c) 2026 Christian Schnuck
// Licensed under the GPL-3.0 (see LICENSE.txt)

using System.Text;
using System.Text.RegularExpressions;

namespace Kx.LanguageKeyGenerator;

public static class LanguageKeyCodeGenerator {
    private static readonly Regex _tokenSeparatorRegex = new("[^A-Za-z0-9]+", RegexOptions.Compiled);
    private static readonly Dictionary<string, string> _tokenOverrides = new(StringComparer.OrdinalIgnoreCase) {
        ["exe"] = "Exe",
        ["id"] = "Id",
        ["ids"] = "Ids",
        ["pkg"] = "Package",
        ["selfupdate"] = "SelfUpdate",
        ["ui"] = "Ui",
        ["url"] = "Url"
    };

    public static string Generate(string yaml, string @namespace, string className, string visibility, string sourcePath) {
        ArgumentException.ThrowIfNullOrWhiteSpace(yaml);
        ArgumentException.ThrowIfNullOrWhiteSpace(@namespace);
        ArgumentException.ThrowIfNullOrWhiteSpace(className);
        ArgumentException.ThrowIfNullOrWhiteSpace(visibility);
        ArgumentException.ThrowIfNullOrWhiteSpace(sourcePath);

        var root = ParseYamlTree(yaml);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Copyright (c) 2026 Christian Schnuck");
        builder.AppendLine("// Licensed under the GPL-3.0 (see LICENSE.txt)");
        builder.AppendLine();
        builder.AppendLine("using Kx.Core.Localization;");
        builder.AppendLine();
        builder.AppendLine($"namespace {@namespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Provides strongly typed localization keys generated from '{NormalizePath(sourcePath)}'.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"{visibility} static class {className} {{");

        foreach (var child in root.Children.Values)
            AppendNode(builder, child, 1, visibility);

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static LanguageNode ParseYamlTree(string yaml) {
        var root = new LanguageNode(name: string.Empty, path: string.Empty);
        var stack = new Stack<(int Indent, LanguageNode Node)>();
        stack.Push((-1, root));

        foreach (string rawLine in yaml.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n')) {
            if (string.IsNullOrWhiteSpace(rawLine))
                continue;

            int indentation = GetIndentation(rawLine);
            string content = rawLine.Trim();
            if (content.StartsWith('#'))
                continue;

            int separatorIndex = content.IndexOf(':');
            if (separatorIndex < 0)
                continue;

            string key = content[..separatorIndex].Trim();
            if (string.IsNullOrWhiteSpace(key))
                continue;

            while (stack.Peek().Indent >= indentation)
                stack.Pop();

            var parent = stack.Peek().Node;
            string keyPath = string.IsNullOrEmpty(parent.Path) ? key : $"{parent.Path}.{key}";
            var node = new LanguageNode(key, keyPath);
            parent.Children[key] = node;

            string valuePortion = content[(separatorIndex + 1)..].Trim();
            if (string.IsNullOrEmpty(valuePortion)) {
                stack.Push((indentation, node));
                continue;
            }

            node.IsLeaf = true;
        }

        return root;
    }

    private static void AppendNode(StringBuilder builder, LanguageNode node, int indentationLevel, string visibility) {
        string indent = new(' ', indentationLevel * 4);
        string name = ToIdentifier(node.Name);

        if (node.IsLeaf && node.Children.Count == 0) {
            builder.AppendLine($"{indent}public static LanguageKey {name} {{ get; }} = new(\"{EscapeString(node.Path)}\");");
            return;
        }

        builder.AppendLine($"{indent}public static class {name} {{");

        foreach (var child in node.Children.Values)
            AppendNode(builder, child, indentationLevel + 1, visibility);

        builder.AppendLine($"{indent}}}");
    }

    private static int GetIndentation(string line) {
        int indentation = 0;
        while (indentation < line.Length && line[indentation] == ' ')
            indentation++;

        return indentation;
    }

    private static string ToIdentifier(string rawName) {
        string[] tokens = _tokenSeparatorRegex
            .Split(rawName)
            .Where(static token => !string.IsNullOrWhiteSpace(token))
            .ToArray();

        if (tokens.Length == 0)
            return "Key";

        var builder = new StringBuilder();
        foreach (string token in tokens) {
            if (_tokenOverrides.TryGetValue(token, out string? replacement)) {
                builder.Append(replacement);
                continue;
            }

            string normalized = token.ToLowerInvariant();
            builder.Append(char.ToUpperInvariant(normalized[0]));
            if (normalized.Length > 1)
                builder.Append(normalized[1..]);
        }

        if (builder.Length == 0)
            return "Key";

        if (char.IsDigit(builder[0]))
            builder.Insert(0, "Key");

        return builder.ToString();
    }

    private static string EscapeString(string value) {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string NormalizePath(string sourcePath) {
        return sourcePath.Replace('\\', '/');
    }

    private sealed class LanguageNode(string name, string path) {
        public string Name { get; } = name;
        public string Path { get; } = path;
        public bool IsLeaf { get; set; }
        public SortedDictionary<string, LanguageNode> Children { get; } = new(StringComparer.OrdinalIgnoreCase);
    }
}
